# Este workflow realiza o push da branch master para um repositório remoto do GitHub 
# quando é dispado o evento de Pull Request na branch master.
#
# References:
#   - https://github.com/marketplace/actions/github-push
#   - https://github.community/t/push-built-files-to-repo-using-actions/18186/5
#   - https://laravel-news.com/push-deploy-with-github-actions


name: GitHub Push to Central Master Repository

on:
  workflow_dispatch

env:
  GITHUB_REMOTE_USERNAME: "central-master"
  GITHUB_REMOTE_EMAIL: "admin@centralmaster.com.br"
  GITHUB_REMOTE_REPOSITORY: "db-migrations-dbfespi"
  GITHUB_REMOTE_TOKEN: ${{ secrets.GHB_REMOTE_TOKEN }}

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    
    - name: User data settings
      run: |
        git config --local user.email "$GITHUB_REMOTE_EMAIL"
        git config --local user.name "$GITHUB_REMOTE_USERNAME"
    
    - name: Connect with remote repository
      run: |
        git remote remove origin
        git remote add origin "https://$GITHUB_REMOTE_USERNAME:$GITHUB_REMOTE_TOKEN@github.com/$GITHUB_REMOTE_USERNAME/$GITHUB_REMOTE_REPOSITORY"
        git fetch origin master
        
    - name: GitIgnore settings
      run: |
        echo ".github/workflows/push_github_remote.yml" >> .gitignore
        echo ".gitignore" >> .gitignore
        echo ".env-template" >> .gitignore
        echo "README.md" >> .gitignore
        cat .gitignore
        
    - name: Commit files
      run: |
        git rm -rf --cached .
        git add -A
        git commit -m "GitHub Action Push"
    
    - name: Push to remote repository
      run: |
        git push origin master --force
